### ISSUE TITLE
memory issue with matlab and large tractograms

### ISSUE THREAD

**Issue by bacaron** [brainlife/app-life#8]
This issue has come up multiple times before, but I just ran into this issue again trying to run LiFE on a tractogram with 1,000,225 streamlines. Did we have a fix for this?

See error log:

+ export MAXMEM=19000000
+ MAXMEM=19000000
+ singularity exec docker://brainlife/mcr:neurodebian1604-r2017a ./compiled/main
WARNING: docker-extract failed, missing executable or libarchive
WARNING: Will use old layer extraction method - this does not handle whiteouts
du: cannot access `./.mcrCache9.2/main_F0/.deploy_write_lock': No such file or directory
Traceback (most recent call last):
  File "/N/u/brlife/Karst/abcd-spec/hooks/pbs/smon", line 137, in <module>
    out=subprocess.check_output(["du", "-s"])
  File "/N/soft/rhel6/python/2.7.16/lib/python2.7/subprocess.py", line 223, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['du', '-s']' returned non-zero exit status 1
++ WARNING: nifti_read_buffer(../5e2c61f301fb3770f7d3fefa/5e2bf15f5778ba23d50f7010/dwi.nii.gz):
   data bytes needed = 427739904
   data bytes input  = 427739904
   number missing    = 0 (set to 0)
Error using horzcat
Out of memory. Type HELP MEMORY for your options.

Error in fefgGet (line 223)

Error in feSet (line 75)

Error in feConnectomeInit (line 52)

Error in life (line 10)

Error in main (line 32)

MATLAB:nomem
/var/spool/torque/mom_priv/jobs/4978970.m2.SC: line 14: kill: (20674) - No such process

**Comment by francopestilli** [comment]
@bacaron let's look into:
(1) The branch was used to build the container. This is likely not the problem, but good to check.
(2) Play around with this: https://github.com/brain-life/encode/commit/d647ab5bcd9d4dcd4066031d184abeb42b5d1830#diff-ec249f87762491ff8080296db6060716R29

**Comment by soichih** [comment]
I can't remember exactly, but I believe app-life v1.9 is not recompiled
with the low-mem version of vistasoft/mex code. I just looked and
app-life<master> version *is* using the patched version of vistasoft. I
don't know why I didn't release 1.10 with it, but I am guessing it because
either 1) we didn't need low-mem version for app-life yet, or 2) I've
tested it and something went wrong?

Can you try running master branch version and see what happens?
